# Generated by Django 4.1.1 on 2023-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0011_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-p3.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
