# Generated by Django 4.1.1 on 2023-02-02 18:41

import ToDoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0012_alter_profile_image_alter_todomodel_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='article_background_colour',
            field=models.CharField(default=ToDoApp.models.TodoModel.colour_choices, max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-p7.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
