# Generated by Django 4.1.1 on 2023-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0013_todomodel_article_background_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-p4.png', upload_to='profile_pics'),
        ),
    ]
